import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'An example movie page',
  description: 'Generated by create next app',
};

// A nested layout component
// https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates#nesting-layouts
export default function MovieLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className='flex min-h-screen flex-col items-center justify-between p-4 md:p-24'>
      {children}
    </section>
  );
}
